[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-cli"
version = "0.0.1"
description = 'My package description'
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = ["mykeywords"]
authors = [{ name = "My Name", email = "my.email@test.com" }]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Environment :: Console",
  "License :: OSI Approved :: MIT License",
]

dependencies = [
  "typer[all]==0.9.0",
]

[project.urls]
Documentation = "https://github.com/mygithubuser/mycli#readme"
Issues = "https://github.com/mygithubuser/mycli/issues"
Source = "https://github.com/mygithubuser/mycli"

[project.optional-dependencies]
dev = [
  "bandit[toml]==1.7.4",
  "black==22.12.0",
  "flake8-bugbear==23.5.9",
  "flake8-builtins==2.1.0",
  "flake8-comprehensions==3.12.0",
  "flake8-docstrings==1.7.0",
  "flake8-encodings[classes]==0.5.0.post1",
  "flake8-return==1.2.0",
  "flake8-simplify==0.19.3",
  "flake8==6.0.0",
  "isort==5.11.4",
  "mypy==1.2.0",
  "pep8-naming==0.13.3",
  "types-PyYAML==6.0.12.9",
]
test = [
  "pytest-cov==4.0.0",
  "pytest==7.2.0",
]

[project.scripts]
my-cli = "my_cli.cli:app"

[tool.hatch.build]
artifacts = [
  "my-cli/static/**",
]

[tool.hatch.envs.dev]
features = ["dev"]

[tool.hatch.envs.test]
features = ["test"]

[tool.hatch.envs.default.scripts]
lint = [
  "flake8 .",
  "mypy . --check-untyped-defs",
  "bandit -qr -c pyproject.toml .",
  "black . --check --diff",
  "isort . --check-only --diff",
]
fmt = [
  "isort .",
  "black .",
  "check",
]
test = [
  "pytest -v",
]
cov = [
  "pytest -v --cov my_cli --cov-report xml --cov-fail-under=80",
]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.mypy]
strict = true

[tool.isort]
profile = "black"
